os: Visual Studio 2019

platform:
  - x86

environment:
  matrix:
    - ARCH: x86
    - ARCH: x64

skip_branch_with_pr: true

install:
  - set PATH=C:\Python311;C:\Python311\Scripts;%PATH%
  - python -m pip install meson ninja

  - call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" %ARCH%

build_script:
  - meson -Ddocs=false --backend=ninja --default-library=both build
  - ninja -C build

test_script:
  - ninja -C build test

artifacts:
  - path: '**\*.dll'
  
  - path: '**\*.lib'
  
  - path: '**\*.a'
  
  - path: 'build\lib\fribidi-config.h'
  
  - path: '**\fribidi-unicode-version.h'
